// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: employee/employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Employees (of Our Customers)
type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int32                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CompanyId     int32                  `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Foreign Key to Companies
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CaimAccount   bool                   `protobuf:"varint,7,opt,name=caim_account,json=caimAccount,proto3" json:"caim_account,omitempty"`
	CaimRole      string                 `protobuf:"bytes,8,opt,name=caim_role,json=caimRole,proto3" json:"caim_role,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Employee) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Employee) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Employee) GetCaimAccount() bool {
	if x != nil {
		return x.CaimAccount
	}
	return false
}

func (x *Employee) GetCaimRole() string {
	if x != nil {
		return x.CaimRole
	}
	return ""
}

func (x *Employee) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Employee) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_employee_employee_proto protoreflect.FileDescriptor

const file_employee_employee_proto_rawDesc = "" +
	"\n" +
	"\x17employee/employee.proto\x12\x03crm\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\bEmployee\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x05R\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x05R\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12!\n" +
	"\fcaim_account\x18\a \x01(\bR\vcaimAccount\x12\x1b\n" +
	"\tcaim_role\x18\b \x01(\tR\bcaimRole\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB,Z*github.com/reidelkins/caim_protos/employeeb\x06proto3"

var (
	file_employee_employee_proto_rawDescOnce sync.Once
	file_employee_employee_proto_rawDescData []byte
)

func file_employee_employee_proto_rawDescGZIP() []byte {
	file_employee_employee_proto_rawDescOnce.Do(func() {
		file_employee_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_employee_proto_rawDesc), len(file_employee_employee_proto_rawDesc)))
	})
	return file_employee_employee_proto_rawDescData
}

var file_employee_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_employee_employee_proto_goTypes = []any{
	(*Employee)(nil),              // 0: crm.Employee
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_employee_employee_proto_depIdxs = []int32{
	1, // 0: crm.Employee.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: crm.Employee.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_employee_employee_proto_init() }
func file_employee_employee_proto_init() {
	if File_employee_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_employee_proto_rawDesc), len(file_employee_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employee_employee_proto_goTypes,
		DependencyIndexes: file_employee_employee_proto_depIdxs,
		MessageInfos:      file_employee_employee_proto_msgTypes,
	}.Build()
	File_employee_employee_proto = out.File
	file_employee_employee_proto_goTypes = nil
	file_employee_employee_proto_depIdxs = nil
}
