// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: employee/employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Employees (of Our Customers)
type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int32                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CompanyId     int32                  `protobuf:"varint,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Foreign Key to Companies
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	CaimAccount   bool                   `protobuf:"varint,7,opt,name=caim_account,json=caimAccount,proto3" json:"caim_account,omitempty"`
	CaimRole      string                 `protobuf:"bytes,8,opt,name=caim_role,json=caimRole,proto3" json:"caim_role,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *Employee) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Employee) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Employee) GetCaimAccount() bool {
	if x != nil {
		return x.CaimAccount
	}
	return false
}

func (x *Employee) GetCaimRole() string {
	if x != nil {
		return x.CaimRole
	}
	return ""
}

func (x *Employee) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Employee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Employee) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int32                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_employee_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetEmployeeRequest) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type GetEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeResponse) Reset() {
	*x = GetEmployeeResponse{}
	mi := &file_employee_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeResponse) ProtoMessage() {}

func (x *GetEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type PutEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEmployeeRequest) Reset() {
	*x = PutEmployeeRequest{}
	mi := &file_employee_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEmployeeRequest) ProtoMessage() {}

func (x *PutEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEmployeeRequest.ProtoReflect.Descriptor instead.
func (*PutEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{3}
}

func (x *PutEmployeeRequest) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type PutEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutEmployeeResponse) Reset() {
	*x = PutEmployeeResponse{}
	mi := &file_employee_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEmployeeResponse) ProtoMessage() {}

func (x *PutEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEmployeeResponse.ProtoReflect.Descriptor instead.
func (*PutEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{4}
}

func (x *PutEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int32                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_employee_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEmployeeRequest) GetEmployeeId() int32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type DeleteEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeResponse) Reset() {
	*x = DeleteEmployeeResponse{}
	mi := &file_employee_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeResponse) ProtoMessage() {}

func (x *DeleteEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_employee_proto_rawDescGZIP(), []int{6}
}

var File_employee_employee_proto protoreflect.FileDescriptor

const file_employee_employee_proto_rawDesc = "" +
	"\n" +
	"\x17employee/employee.proto\x12\x03crm\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\bEmployee\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x05R\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x05R\tcompanyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12!\n" +
	"\fcaim_account\x18\a \x01(\bR\vcaimAccount\x12\x1b\n" +
	"\tcaim_role\x18\b \x01(\tR\bcaimRole\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"5\n" +
	"\x12GetEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x05R\n" +
	"employeeId\"@\n" +
	"\x13GetEmployeeResponse\x12)\n" +
	"\bemployee\x18\x01 \x01(\v2\r.crm.EmployeeR\bemployee\"?\n" +
	"\x12PutEmployeeRequest\x12)\n" +
	"\bemployee\x18\x01 \x01(\v2\r.crm.EmployeeR\bemployee\"@\n" +
	"\x13PutEmployeeResponse\x12)\n" +
	"\bemployee\x18\x01 \x01(\v2\r.crm.EmployeeR\bemployee\"8\n" +
	"\x15DeleteEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x05R\n" +
	"employeeId\"\x18\n" +
	"\x16DeleteEmployeeResponse2\xe0\x01\n" +
	"\x0fEmployeeService\x12@\n" +
	"\vGetEmployee\x12\x17.crm.GetEmployeeRequest\x1a\x18.crm.GetEmployeeResponse\x12@\n" +
	"\vPutEmployee\x12\x17.crm.PutEmployeeRequest\x1a\x18.crm.PutEmployeeResponse\x12I\n" +
	"\x0eDeleteEmployee\x12\x1a.crm.DeleteEmployeeRequest\x1a\x1b.crm.DeleteEmployeeResponseB,Z*github.com/reidelkins/caim_protos/employeeb\x06proto3"

var (
	file_employee_employee_proto_rawDescOnce sync.Once
	file_employee_employee_proto_rawDescData []byte
)

func file_employee_employee_proto_rawDescGZIP() []byte {
	file_employee_employee_proto_rawDescOnce.Do(func() {
		file_employee_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_employee_proto_rawDesc), len(file_employee_employee_proto_rawDesc)))
	})
	return file_employee_employee_proto_rawDescData
}

var file_employee_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_employee_employee_proto_goTypes = []any{
	(*Employee)(nil),               // 0: crm.Employee
	(*GetEmployeeRequest)(nil),     // 1: crm.GetEmployeeRequest
	(*GetEmployeeResponse)(nil),    // 2: crm.GetEmployeeResponse
	(*PutEmployeeRequest)(nil),     // 3: crm.PutEmployeeRequest
	(*PutEmployeeResponse)(nil),    // 4: crm.PutEmployeeResponse
	(*DeleteEmployeeRequest)(nil),  // 5: crm.DeleteEmployeeRequest
	(*DeleteEmployeeResponse)(nil), // 6: crm.DeleteEmployeeResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_employee_employee_proto_depIdxs = []int32{
	7, // 0: crm.Employee.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: crm.Employee.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: crm.GetEmployeeResponse.employee:type_name -> crm.Employee
	0, // 3: crm.PutEmployeeRequest.employee:type_name -> crm.Employee
	0, // 4: crm.PutEmployeeResponse.employee:type_name -> crm.Employee
	1, // 5: crm.EmployeeService.GetEmployee:input_type -> crm.GetEmployeeRequest
	3, // 6: crm.EmployeeService.PutEmployee:input_type -> crm.PutEmployeeRequest
	5, // 7: crm.EmployeeService.DeleteEmployee:input_type -> crm.DeleteEmployeeRequest
	2, // 8: crm.EmployeeService.GetEmployee:output_type -> crm.GetEmployeeResponse
	4, // 9: crm.EmployeeService.PutEmployee:output_type -> crm.PutEmployeeResponse
	6, // 10: crm.EmployeeService.DeleteEmployee:output_type -> crm.DeleteEmployeeResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_employee_employee_proto_init() }
func file_employee_employee_proto_init() {
	if File_employee_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_employee_proto_rawDesc), len(file_employee_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_employee_proto_goTypes,
		DependencyIndexes: file_employee_employee_proto_depIdxs,
		MessageInfos:      file_employee_employee_proto_msgTypes,
	}.Build()
	File_employee_employee_proto = out.File
	file_employee_employee_proto_goTypes = nil
	file_employee_employee_proto_depIdxs = nil
}
