// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address message to represent company address details.
type Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The street address.
	Street string `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	// Apartment number or other specific information
	Street2 string `protobuf:"bytes,2,opt,name=street2,proto3" json:"street2,omitempty"`
	// The city.
	City string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	// The state or province.
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// The postal or zip code.
	ZipCode string `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	// The country.
	Country       string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_address_address_proto protoreflect.FileDescriptor

const file_address_address_proto_rawDesc = "" +
	"\n" +
	"\x15address/address.proto\x12\x03crm\"\x9a\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x18\n" +
	"\astreet2\x18\x02 \x01(\tR\astreet2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x05 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountryB+Z)github.com/reidelkins/caim_protos/addressb\x06proto3"

var (
	file_address_address_proto_rawDescOnce sync.Once
	file_address_address_proto_rawDescData []byte
)

func file_address_address_proto_rawDescGZIP() []byte {
	file_address_address_proto_rawDescOnce.Do(func() {
		file_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_address_proto_rawDesc), len(file_address_address_proto_rawDesc)))
	})
	return file_address_address_proto_rawDescData
}

var file_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_address_address_proto_goTypes = []any{
	(*Address)(nil), // 0: crm.Address
}
var file_address_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_address_address_proto_init() }
func file_address_address_proto_init() {
	if File_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_address_proto_rawDesc), len(file_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_address_address_proto_goTypes,
		DependencyIndexes: file_address_address_proto_depIdxs,
		MessageInfos:      file_address_address_proto_msgTypes,
	}.Build()
	File_address_address_proto = out.File
	file_address_address_proto_goTypes = nil
	file_address_address_proto_depIdxs = nil
}
