// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: company/company.proto

package company

import (
	address "github.com/reidelkins/caim_protos/address"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Companies (Our Customers)
type Company struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the company.
	CompanyId int32 `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Name of the company.
	CompanyName string `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// Address of the company.
	CompanyAddress *address.Address `protobuf:"bytes,3,opt,name=company_address,json=companyAddress,proto3" json:"company_address,omitempty"`
	// Phone number of the company.
	CompanyPhone string `protobuf:"bytes,4,opt,name=company_phone,json=companyPhone,proto3" json:"company_phone,omitempty"`
	// Email address of the company.
	CompanyEmail string `protobuf:"bytes,5,opt,name=company_email,json=companyEmail,proto3" json:"company_email,omitempty"`
	// Type of subscription the company has.
	SubscriptionType string `protobuf:"bytes,6,opt,name=subscription_type,json=subscriptionType,proto3" json:"subscription_type,omitempty"`
	// Date when the subscription started.
	SubscriptionStartDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=subscription_start_date,json=subscriptionStartDate,proto3" json:"subscription_start_date,omitempty"`
	// Date when the subscription ends.
	SubscriptionEndDate *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=subscription_end_date,json=subscriptionEndDate,proto3" json:"subscription_end_date,omitempty"`
	// Date when the company was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Company) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Company) GetCompanyAddress() *address.Address {
	if x != nil {
		return x.CompanyAddress
	}
	return nil
}

func (x *Company) GetCompanyPhone() string {
	if x != nil {
		return x.CompanyPhone
	}
	return ""
}

func (x *Company) GetCompanyEmail() string {
	if x != nil {
		return x.CompanyEmail
	}
	return ""
}

func (x *Company) GetSubscriptionType() string {
	if x != nil {
		return x.SubscriptionType
	}
	return ""
}

func (x *Company) GetSubscriptionStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionStartDate
	}
	return nil
}

func (x *Company) GetSubscriptionEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SubscriptionEndDate
	}
	return nil
}

func (x *Company) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request message for GetCompany
type GetCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int32                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRequest) Reset() {
	*x = GetCompanyRequest{}
	mi := &file_company_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRequest) ProtoMessage() {}

func (x *GetCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1}
}

func (x *GetCompanyRequest) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

// Request message for PutCompany
type PutCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       *Company               `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutCompanyRequest) Reset() {
	*x = PutCompanyRequest{}
	mi := &file_company_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCompanyRequest) ProtoMessage() {}

func (x *PutCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCompanyRequest.ProtoReflect.Descriptor instead.
func (*PutCompanyRequest) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{2}
}

func (x *PutCompanyRequest) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

var File_company_company_proto protoreflect.FileDescriptor

const file_company_company_proto_rawDesc = "" +
	"\n" +
	"\x15company/company.proto\x12\x03crm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15address/address.proto\"\xd8\x03\n" +
	"\aCompany\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x05R\tcompanyId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x125\n" +
	"\x0fcompany_address\x18\x03 \x01(\v2\f.crm.AddressR\x0ecompanyAddress\x12#\n" +
	"\rcompany_phone\x18\x04 \x01(\tR\fcompanyPhone\x12#\n" +
	"\rcompany_email\x18\x05 \x01(\tR\fcompanyEmail\x12+\n" +
	"\x11subscription_type\x18\x06 \x01(\tR\x10subscriptionType\x12R\n" +
	"\x17subscription_start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x15subscriptionStartDate\x12N\n" +
	"\x15subscription_end_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x13subscriptionEndDate\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"2\n" +
	"\x11GetCompanyRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x05R\tcompanyId\";\n" +
	"\x11PutCompanyRequest\x12&\n" +
	"\acompany\x18\x01 \x01(\v2\f.crm.CompanyR\acompany2x\n" +
	"\x0eCompanyService\x122\n" +
	"\n" +
	"GetCompany\x12\x16.crm.GetCompanyRequest\x1a\f.crm.Company\x122\n" +
	"\n" +
	"PutCompany\x12\x16.crm.PutCompanyRequest\x1a\f.crm.CompanyB+Z)github.com/reidelkins/caim_protos/companyb\x06proto3"

var (
	file_company_company_proto_rawDescOnce sync.Once
	file_company_company_proto_rawDescData []byte
)

func file_company_company_proto_rawDescGZIP() []byte {
	file_company_company_proto_rawDescOnce.Do(func() {
		file_company_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_company_proto_rawDesc), len(file_company_company_proto_rawDesc)))
	})
	return file_company_company_proto_rawDescData
}

var file_company_company_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_company_company_proto_goTypes = []any{
	(*Company)(nil),               // 0: crm.Company
	(*GetCompanyRequest)(nil),     // 1: crm.GetCompanyRequest
	(*PutCompanyRequest)(nil),     // 2: crm.PutCompanyRequest
	(*address.Address)(nil),       // 3: crm.Address
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_company_company_proto_depIdxs = []int32{
	3, // 0: crm.Company.company_address:type_name -> crm.Address
	4, // 1: crm.Company.subscription_start_date:type_name -> google.protobuf.Timestamp
	4, // 2: crm.Company.subscription_end_date:type_name -> google.protobuf.Timestamp
	4, // 3: crm.Company.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: crm.PutCompanyRequest.company:type_name -> crm.Company
	1, // 5: crm.CompanyService.GetCompany:input_type -> crm.GetCompanyRequest
	2, // 6: crm.CompanyService.PutCompany:input_type -> crm.PutCompanyRequest
	0, // 7: crm.CompanyService.GetCompany:output_type -> crm.Company
	0, // 8: crm.CompanyService.PutCompany:output_type -> crm.Company
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_company_company_proto_init() }
func file_company_company_proto_init() {
	if File_company_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_company_proto_rawDesc), len(file_company_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_company_company_proto_goTypes,
		DependencyIndexes: file_company_company_proto_depIdxs,
		MessageInfos:      file_company_company_proto_msgTypes,
	}.Build()
	File_company_company_proto = out.File
	file_company_company_proto_goTypes = nil
	file_company_company_proto_depIdxs = nil
}
